### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by ProjectJiren** [gliesefire/MyProjects#1]
I know this is probably something that is just for you and your projects, but i was searching for a way to automate the captcha. I'm more of a C# person and learning how python works is awesome so this is cool for me. 

Looking into what you did you take a screen shot and then dice it up accordingly based upon where it's imageElement.Location is.

When I use it and check:

cropped = pageScreenshot[loc['y']:loc['y'] + 214 , loc['x']:loc['x'] + 320]

it takes a blank picture. My resolution is 2560x1600 and the screenshot ends up being 2560x1292.
I was thinking of taking that, doing some calculations and getting the correct images so the program can continue but it would never end up being 320x214. 

So this is the part where I am stuck at.

If you'd like to talk about this privately please message me on discord. NightWing#1529

**Comment by gliesefire** [comment]
**Few Context setting here**

> I  **know** that the captcha image returned by server has resolution of 320x214, hence I hardcoded it. If your captcha has a different resolution, use that instead of 320x214.

> webdriver takes screenshot of the area occupied by the webpage only.  So even if you have start with maximized window, the area consumed by your Windows taskbar, browser's address Bar ,title bar etc would be excluded from the screenshot. *Probably the reason why you are missing that 318 pixels*
Play with the size of your browser window and take screenshots, you would understand yourself how it works.

> the code is independent of screen resolution. The imageElement.Location is dependent on the screenshot resolution, which in turn acts an offset for captcha image.
